// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbazahjtivfmescwxpro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiYXphaGp0aXZmbWVzY3d4cHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTQ3MzUsImV4cCI6MjA3MTk3MDczNX0.vc2rjWKOgSoGq4Csv4Qk85cKrDYWlrVWOfIe-9ne5yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});